### ISSUE TITLE
更换 `FB` 程序下载源 & 增设 `FB` 程序的 `SHA` 检测

### ISSUE THREAD

**Issue by Happy2018new** [SuperScript-PRC/ToolDelta#26]
由 `CMA2401PT` 所编写的 `External` 模块在提交 https://github.com/LNSSPsd/PhoenixBuilder/commit/1b6832329558d0a26e02e27d9fdf01fb2885bd55 被正式移除了，并且开发组正准备编写一个完全不同的 `Websocket API` 模块作为它的替代。

由于 `ToolDelta` 项目普遍依赖于已被移除的 `External` 实现，因此为了保证本项目仍能如期使用，我在 https://github.com/rnhws-Team/ToolDelta-PhoenixBuilder 处的仓库单独提供了 `ToolDelta` 特供版 `PhoenixBuilder` ，以允许往后我们仍能使用已被移除的 `External` 模块。

因此，我们需要更换下载源为 https://github.com/rnhws-Team/ToolDelta-PhoenixBuilder ，并且增设一个 `SHA` 检测以确保用户使用的是 `特供版` 而非从官方仓库下载的 `PhoenixBuilder` 。

我最多能做的就是维护仓库 https://github.com/rnhws-Team/ToolDelta-PhoenixBuilder ——我目前仅剩的周末时间已然不再允许我做更多的事情，我对此感到抱歉，希望你们都可以理解。

**Comment by SuperScript-PRC** [comment]
WebSocketAPI 有示例吗？这个项目有可能可以抛弃External而使用WSAPI

**Comment by SuperScript-PRC** [comment]
否则..就不能轻松地在每次PhioenixBuilder更新的时候使用其了

**Comment by SuperScript-PRC** [comment]
鉴于rnhws-ToolDelta项目已归档，已关闭该issue。
