### ISSUE TITLE
[Bug?] 部署遇到的问题

### ISSUE THREAD

**Issue by wling-art** [SuperScript-PRC/ToolDelta#27]
在 https://github.com/SuperScript-PRC/ToolDelta/commit/5960f46b6ad8308b339f535ee40aa6aa57a0edc1 的更改后部署出现问题

这里变量名是不是应该为PacketIDS？
https://github.com/SuperScript-PRC/ToolDelta/blob/5ef27118deba2aba6ce8738273e14d8339d8a927/libs/packets.py#L1
貌似项目中应该需要导入这个模块的这个内容
https://github.com/SuperScript-PRC/ToolDelta/blob/5ef27118deba2aba6ce8738273e14d8339d8a927/ToolDelta.py#L12
https://github.com/SuperScript-PRC/ToolDelta/blob/5ef27118deba2aba6ce8738273e14d8339d8a927/libs/launch_cli.py#L8

下面是不是缺少相关的链接库？
https://github.com/SuperScript-PRC/ToolDelta/blob/5ef27118deba2aba6ce8738273e14d8339d8a927/libs/neo_conn.py#L52-L63

**Comment by SuperScript-PRC** [comment]
似乎没有把部署库放到repo里...

**Comment by SuperScript-PRC** [comment]
> 似乎没有把部署库放到repo里...

我想想应该放到releases里还是libs/下

**Comment by SuperScript-PRC** [comment]
> 在 [5960f46](https://github.com/SuperScript-PRC/ToolDelta/commit/5960f46b6ad8308b339f535ee40aa6aa57a0edc1) 的更改后部署出现问题
> 
> 这里变量名是不是应该为PacketIDS？
> 
> https://github.com/SuperScript-PRC/ToolDelta/blob/5ef27118deba2aba6ce8738273e14d8339d8a927/libs/packets.py#L1
> 
> 
> 貌似项目中应该需要导入这个模块的这个内容
> https://github.com/SuperScript-PRC/ToolDelta/blob/5ef27118deba2aba6ce8738273e14d8339d8a927/ToolDelta.py#L12
> 
> 
> https://github.com/SuperScript-PRC/ToolDelta/blob/5ef27118deba2aba6ce8738273e14d8339d8a927/libs/launch_cli.py#L8
> 
> 下面是不是缺少相关的链接库？
> 
> https://github.com/SuperScript-PRC/ToolDelta/blob/5ef27118deba2aba6ce8738273e14d8339d8a927/libs/neo_conn.py#L52-L63

PacketIDS应当是一个常数集类型，指明各种数据包对应的类型，或许是没来得及提交更新
